[2024-11-30T18:44:25.276+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-30T18:44:25.283+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_income_aggregate.update_income_aggregate manual__2024-11-30T18:44:23.139260+00:00 [queued]>
[2024-11-30T18:44:25.286+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_income_aggregate.update_income_aggregate manual__2024-11-30T18:44:23.139260+00:00 [queued]>
[2024-11-30T18:44:25.287+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-30T18:44:25.292+0000] {taskinstance.py:2889} INFO - Executing <Task(ClickHouseOperator): update_income_aggregate> on 2024-11-30 18:44:23.139260+00:00
[2024-11-30T18:44:25.297+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-30T18:44:25.298+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2024-11-30T18:44:25.299+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'update_income_aggregate', 'update_income_aggregate', 'manual__2024-11-30T18:44:23.139260+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpmcbn6zz3']
[2024-11-30T18:44:25.299+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask update_income_aggregate
[2024-11-30T18:44:25.320+0000] {task_command.py:467} INFO - Running <TaskInstance: update_income_aggregate.update_income_aggregate manual__2024-11-30T18:44:23.139260+00:00 [running]> on host 66a40688d358
[2024-11-30T18:44:25.489+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_income_aggregate' AIRFLOW_CTX_TASK_ID='update_income_aggregate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T18:44:23.139260+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T18:44:23.139260+00:00'
[2024-11-30T18:44:25.490+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-30T18:44:25.490+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-30T18:44:25.490+0000] {logging_mixin.py:190} INFO - Current task name:update_income_aggregate state:running start_date:2024-11-30 18:44:25.284260+00:00
[2024-11-30T18:44:25.490+0000] {logging_mixin.py:190} INFO - Dag name:update_income_aggregate and current dag run status:running
[2024-11-30T18:44:25.490+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-30T18:44:25.494+0000] {base.py:84} INFO - Retrieving connection 'clickhouse_test'
[2024-11-30T18:44:25.494+0000] {clickhouse.py:79} INFO - INSERT INTO daily_events_*** (date, operation, count) SELECT toDate(FROM_UNIXTIME(ts)) AS date, operation, count() AS count FROM events GROUP BY date, operation
[2024-11-30T18:44:25.502+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 382, in execute
    rv = self.process_ordinary_query(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 212, in receive_result
    return result.get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 228, in packet_generator
    packet = self.receive_packet()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 245, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 16.
DB::Exception: No such column count in table default.daily_events_airflow (d39f7188-9563-4c35-a070-f3dde839145a). Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc03b04
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cd17c
2. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x0000000007b3eb5c
3. DB::InterpreterInsertQuery::getSampleBlockImpl(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool) @ 0x000000000fd1c1a0
4. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x000000000fd1b6a0
5. DB::InterpreterInsertQuery::execute() @ 0x000000000fd21150
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000010043494
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001003fde8
8. DB::TCPHandler::runImpl() @ 0x000000001100835c
9. DB::TCPHandler::run() @ 0x000000001101d7e4
10. Poco::Net::TCPServerConnection::start() @ 0x0000000013892078
11. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013892554
12. Poco::PooledThread::run() @ 0x000000001385d0b8
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001385b4f0
14. ? @ 0x000000000007d5c8
15. ? @ 0x00000000000e5edc

[2024-11-30T18:44:25.506+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-30T18:44:25.507+0000] {logging_mixin.py:190} INFO - Task start:2024-11-30 18:44:25.284260+00:00 end:2024-11-30 18:44:25.506741+00:00 duration:0.222481
[2024-11-30T18:44:25.507+0000] {logging_mixin.py:190} INFO - Task:<Task(ClickHouseOperator): update_income_aggregate> dag:<DAG: update_income_aggregate> dagrun:<DagRun update_income_aggregate @ 2024-11-30 18:44:23.139260+00:00: manual__2024-11-30T18:44:23.139260+00:00, state:running, queued_at: 2024-11-30 18:44:23.156409+00:00. externally triggered: True>
[2024-11-30T18:44:25.507+0000] {logging_mixin.py:190} INFO - Failure caused by Code: 16.
DB::Exception: No such column count in table default.daily_events_*** (d39f7188-9563-4c35-a070-f3dde839145a). Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc03b04
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cd17c
2. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x0000000007b3eb5c
3. DB::InterpreterInsertQuery::getSampleBlockImpl(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool) @ 0x000000000fd1c1a0
4. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x000000000fd1b6a0
5. DB::InterpreterInsertQuery::execute() @ 0x000000000fd21150
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000010043494
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001003fde8
8. DB::TCPHandler::runImpl() @ 0x000000001100835c
9. DB::TCPHandler::run() @ 0x000000001101d7e4
10. Poco::Net::TCPServerConnection::start() @ 0x0000000013892078
11. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013892554
12. Poco::PooledThread::run() @ 0x000000001385d0b8
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001385b4f0
14. ? @ 0x000000000007d5c8
15. ? @ 0x00000000000e5edc
[2024-11-30T18:44:25.507+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=update_income_aggregate, task_id=update_income_aggregate, run_id=manual__2024-11-30T18:44:23.139260+00:00, execution_date=20241130T184423, start_date=20241130T184425, end_date=20241130T184425
[2024-11-30T18:44:25.511+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-30T18:44:25.511+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 53 for task update_income_aggregate (Code: 16.
DB::Exception: No such column count in table default.daily_events_airflow (d39f7188-9563-4c35-a070-f3dde839145a). Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc03b04
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cd17c
2. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x0000000007b3eb5c
3. DB::InterpreterInsertQuery::getSampleBlockImpl(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool) @ 0x000000000fd1c1a0
4. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x000000000fd1b6a0
5. DB::InterpreterInsertQuery::execute() @ 0x000000000fd21150
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000010043494
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001003fde8
8. DB::TCPHandler::runImpl() @ 0x000000001100835c
9. DB::TCPHandler::run() @ 0x000000001101d7e4
10. Poco::Net::TCPServerConnection::start() @ 0x0000000013892078
11. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013892554
12. Poco::PooledThread::run() @ 0x000000001385d0b8
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001385b4f0
14. ? @ 0x000000000007d5c8
15. ? @ 0x00000000000e5edc
; 85)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 382, in execute
    rv = self.process_ordinary_query(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 212, in receive_result
    return result.get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 228, in packet_generator
    packet = self.receive_packet()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 245, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 16.
DB::Exception: No such column count in table default.daily_events_airflow (d39f7188-9563-4c35-a070-f3dde839145a). Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bc03b04
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000078cd17c
2. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x0000000007b3eb5c
3. DB::InterpreterInsertQuery::getSampleBlockImpl(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool) @ 0x000000000fd1c1a0
4. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x000000000fd1b6a0
5. DB::InterpreterInsertQuery::execute() @ 0x000000000fd21150
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000010043494
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001003fde8
8. DB::TCPHandler::runImpl() @ 0x000000001100835c
9. DB::TCPHandler::run() @ 0x000000001101d7e4
10. Poco::Net::TCPServerConnection::start() @ 0x0000000013892078
11. Poco::Net::TCPServerDispatcher::run() @ 0x0000000013892554
12. Poco::PooledThread::run() @ 0x000000001385d0b8
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001385b4f0
14. ? @ 0x000000000007d5c8
15. ? @ 0x00000000000e5edc

[2024-11-30T18:44:25.526+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-30T18:44:25.536+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T18:44:25.538+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
